src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404= 'website.views.custom_page_not_found'

src/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home , name="home"), 
    path('logout/', views.logout_user , name="logout"), 
    path('register/', views.register_user , name="register"), 
    path('record/<int:pk>', views.customer_record , name="customer_record"), 
    path('delete_record/<int:pk>', views.delete_record , name="delete_record"), 
    path('add_record/', views.add_record , name="add_record"), 
    path('update_record/<int:pk>', views.update_record , name="update_record"), 
    path('search/', views.search , name="search"), 
    path('profile/', views.profile , name="profile"), 
    path('cause-error/', views.cause_error, name='cause_error'),

]

src/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>CRM</title>
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
   {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> {% endcomment %}
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
   <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css"> 
   <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css"> 
   <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="stylesheet" href="{% static 'fontawesomefree\css\fontawesome.css' %}">
   <script src="https://code.jquery.com/jquery-3.7.1.min.js" ></script>


</head>
<body style="display: flex; flex-direction: column; min-height: 100vh;margin: 0;">
    <div class="content" style="flex: 1;">

    
    {% include 'navbar.html'%}
    <br>
    <div class="container">
        <div class="show-hide">
            {% if messages %}
            {% for message in messages %}
                <div role="alert" class="alert alert-warning alert-dismissible fade show">

                    {{message}}
                    <button class="btn-close" data-bs-dismiss="alert" aria-label="Close" type="button"></button>
                </div>


`              
            {% endfor%}
        {% endif%}
        </div>
        
        {% block content%}
        {% endblock%}
        
    </div>
</div>
    <footer style="margin-top:50px; background-color: black;text-align: center; padding: 20px; text-decoration: none;">
        <h5 style="color: white; margin:30px auto ; font-size:larger ">CRM - Clients Relationships Managements</h5>
        <p class="text-light mt-2">&copy; <span id="year"></span> Developed by <a href="https://github.com/Mohammed-Aljazzar" target="_blank" style="text-decoration: none;">Mohammed Aljazzar</a>. All Rights Reserved.</p>
        
    </footer>
    
</body>
    <script src="{% static 'js/bootstrap.js' %}" ></script>

    <script>
        // Get the current year
        const currentYear = new Date().getFullYear();
    
        // Set it in the footer
        document.getElementById("year").textContent = currentYear;



        $(document).ready(function(){
            setTimeout(function(){
                $('.show-hide').fadeOut('slow');
            }, 3000)
        });
    </script>
</html>

src/templates/navbar.html
{% load static%}
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="#">CRM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="display: flex;align-items: center;">
          
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:home' %}">Dashboard <i class="fa fa-home"></i></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'website:logout' %}">Sign Out <i class="fa fa-fas fa-sign-out-alt"></i></a>
          </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:register'%}">Register <i class="fa fa-fas fa-key"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'website:home'%}">Login <i class="fa fa-fas fa-sign-out-alt"></i></a>
            </li>
          {% endif%}

        </ul>
        {% if user.is_authenticated %}
        <ul style="color: white; list-style: none; font-size:medium;display: flex;align-items: center;">
          <a href="{% url 'website:profile'%}" style="text-decoration: none;"><li style="color: white;" class="text-warning">{{request.user.username|capfirst}} <i class="fa fa-fas fa-user-circle" style="font-size: 24px; margin-left: 6px; margin-top: 10px;"></i></li></a>
        </ul>
        {%endif%}
        
      </div>
      
    </div>
  </nav>