src/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404= 'website.views.custom_page_not_found'

src/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home , name="home"), 
    path('logout/', views.logout_user , name="logout"), 
    path('register/', views.register_user , name="register"), 
    path('record/<int:pk>', views.customer_record , name="customer_record"), 
    path('delete_record/<int:pk>', views.delete_record , name="delete_record"), 
    path('add_record/', views.add_record , name="add_record"), 
    path('update_record/<int:pk>', views.update_record , name="update_record"), 
    path('search/', views.search , name="search"), 
    path('profile/', views.profile , name="profile"), 
    path('cause-error/', views.cause_error, name='cause_error'),

]

src/website/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Record(models.Model):
    created_at = models.DateTimeField( auto_now_add=True)
    first_name= models.CharField( max_length=50)
    last_name= models.CharField( max_length=50)
    email= models.EmailField( max_length=50)
    phone= models.CharField( max_length=50)
    address= models.CharField( max_length=50)
    city= models.CharField( max_length=50)
    state= models.CharField( max_length=50)
    zipcode= models.CharField( max_length=10)
    

    def __str__(self):
        return (f"{self.first_name} {self.last_name}")

    class Meta:
        ordering =['-created_at']

src/website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record
class SignUpForm(UserCreationForm):
    email= forms.EmailField(label="Email", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    first_name= forms.CharField(label="First Name",max_length=50, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name= forms.CharField(label="Last Name",max_length=50, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

    class Meta:
        model= User
        fields= ('username', 'first_name','last_name','email','password1','password2') 

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class']='form-control'
        self.fields['username'].widget.attrs['placeholder']='Username'
        self.fields['username'].widget.label='Username'
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'
        self.fields['password1'].widget.attrs['class']='form-control'
        self.fields['password1'].widget.attrs['placeholder']='Password'
        self.fields['password1'].widget.label='Password'
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'        
        self.fields['password2'].widget.attrs['class']='form-control'
        self.fields['password2'].widget.attrs['placeholder']='Confirm Password'
        self.fields['password2'].widget.label='Password'
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	

     


class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(label= "First Name", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(label= "Last Name", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))
     
    email = forms.EmailField(label= "Email", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email'}))
    address = forms.CharField(label= "Address", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address'}))
    phone = forms.CharField(label= "Phone", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone'}))
    city = forms.CharField(label= "City", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'City'}))
    state = forms.CharField(label= "State", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'State'}))
    zipcode = forms.CharField(label= "Zip Code", required=True,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Zip Code'}))

    class Meta:
        model = Record
        exclude = ("user",)

src/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import SignUpForm , AddRecordForm
from .models import Record
import logging
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse 

# Create your views here.

# @login_required(login_url='website:home')
def home(request):
    records = Record.objects.all()


    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        #Authentication 

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            messages.success(request, 'You Have Been Logged In!')
            return redirect('website:home')
        else:
            messages.success(request, 'There Was An Error Logging In, Please Try Again')
            return redirect('website:home')
    else:
        return render(request, 'home.html', {'records':records})

def logout_user(request):
    logout(request)
    messages.success(request, 'You Have Logged Out...')
    return redirect('website:home')

def register_user(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			# Authenticate and login
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username, password=password)
			login(request, user)
			messages.success(request, "You Have Successfully Registered! Welcome!")
			return redirect('website:home')
	else:
		form = SignUpForm()
		return render(request, 'register.html', {'form':form})
	return render(request, 'register.html', {'form':form})



def customer_record(request, pk):
    if request.user.is_authenticated:
        customer_record = Record.objects.get(id=pk)
        return render(request, 'record.html', {'customer_record':customer_record})
    else:
        messages.success(request, 'You Must Be Logged In To View That Page...')
        return redirect('website:home')


def delete_record(request, pk):
     if request.user.is_authenticated:
        delete_it = Record.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, 'Record Deleted Successfully!')
        return redirect('website:home')
     else:
        messages.success(request, 'You Must Be Logged In To Delete That Record...')
        return redirect('website:home')
          
def add_record(request):
        form = AddRecordForm(request.POST or None)
        if request.user.is_authenticated:
            if request.method == "POST":
                if form.is_valid():
                    add_record = form.save()
                    messages.success(request,'Record Added...')
                    return redirect('website:home')
        else:
            messages.success(request,'You Must Be Logged In')
            return redirect('website:home')
        return render(request, 'add_record.html', {'form':form})
     

def update_record(request, pk):
        if request.user.is_authenticated:
            current_record = Record.objects.get(id=pk)
            form = AddRecordForm(request.POST or None, instance=current_record)
            if form.is_valid():
                form.save()
                messages.success(request,'Record Has Been Updated!')
                return redirect('website:home')
            return render(request, 'update_record.html', {'form':form})
        else:
            messages.success(request,'You Must Be Logged In')
            return redirect('website:home')
             


def custom_page_not_found(request,exception):
     return render(request,'404.html',status=404)

logger = logging.getLogger(__name__)

def search(request):
    if request.user.is_authenticated:
        query= request.GET.get('query')
        results =[]
        try:
            if query:
                results= Record.objects.filter(Q(first_name__icontains=query)| Q(last_name__icontains=query) | Q(id__icontains=query))
        except Exception as e:
          logger.error('Error during search: %s',e)
          
        return render(request,'search.html',{'results':results, 'query':query})
    else:
         messages.success(request,'You Must Be Logged In')
         return redirect('website:home')
    
def profile(request):
     if request.user.is_authenticated:
        return render(request,'profile.html',{})
     


def trigger_error(request):
    return render(request, '500.html', status=500)


def cause_error(request):
      # هذا الكود يتسبب في خطأ القسمة على صفر 
      result = 1 / 0 
      return HttpResponse(f"النتيجة: {result}")

src/website/templates/add_record.html
{% extends 'base.html'%}
{% block content%}
<div class="col-md-6 offset-md-3">
    <br>
    <div style="background-color:rgba(189, 189, 189, 0.8); padding: 40px;margin-bottom: 40px;border-radius: 20px;">
        <h3 class="text-dark text-left mb-2" style="font-family: arial;">Add New Record</h3>
        <hr style="background: black;height: 1px;">
        
        <form action="{% url 'website:add_record' %}" method="POST">
            {% csrf_token %}

            {{form.as_p}}
            <a href="{% url 'website:home' %}" class="btn btn-secondary" ><i class="fa fa-fas fa-arrow-left"></i> Back</a>

            <button type="submit" class="btn btn-primary" style=" background-color: black; color:white">Add Record</button>
            
        </form>
</div>
</div>

{% endblock%}

src/website/templates/home.html
{% extends 'base.html'%}
{% block content%}

{% if user.is_authenticated %}
<br>
<h3 class="text-dark pb-3">Welcome to the dashboard page, <span class="text-warning">{{user.username}}</span>!👋</h3>
<hr class="mr-5 ml-5 text-dark" style="height: 1px;">

<br>
{% if request.user.is_superuser%}
<a class="btn btn-dark d-inline-block"  href="{% url 'website:add_record' %}">Create Record <i class="fa fa-fas fa-plus"></i></a>
<br>
<hr class="mr-5 ml-5 text-dark" style="height: 1px;">
{%endif%}
<div class="mt-3" style="">
    <form action="{% url 'website:search'%}" method="GET">
        <input type="search" name="query" placeholder="write something here " class="form-control mb-2">
        <button type="submit" class="btn btn-dark d-block w-100 mb-4">Search <i class="fa fa-fas fa-search"></i></button>
    </form>
</div>

<hr class="mr-5 ml-5 text-dark" style="height: 1px;">
<table class="table table-striped table-hover  table-bordered">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Address</th>
            <th scope="col">City</th>
            <th scope="col">State</th>
            <th scope="col">Created At</th>
            <th scope="col">Zipcode</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% if records %}
            {% for record in records %}
                <tr>
                    <td>{{record.id}}</td>
                    <td>{{record.first_name}}</td>
                    <td>{{record.last_name}}</td>
                    <td>{{record.email}}</td>
                    <td>{{record.phone}}</td>
                    <td>{{record.address}}</td>
                    <td>{{record.city}}</td>
                    <td>{{record.state}}</td>
                    <td>{{record.created_at| date:"Y M d"}}</td>
                    <td>{{record.zipcode}}</td>
                    <td><a href="{% url 'website:customer_record' record.id %}" class="fa-solid fa-eye text-secondary" style="color:black; text-decoration: none;"></a></td>
                </tr>
            {% endfor %}
        {% else %}
        <td colspan="11" class="text-center p-3" style="background-color: #fef2cc;">
           <span style="font-weight: 500; font-size:large;"> There are no records yet!</span>
        </td>
        {% endif %}
            
    </tbody>



</table>

    


{% else %}
<div class="col-md-6 offset-md-3 mt-3">
<div style="background-color:rgba(189, 189, 189, 0.8); padding: 40px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); margin-bottom: 20px;border-radius: 20px;">

<form action="{% url 'website:home' %}" method="POST" autocomplete='off'>
    {% csrf_token %}
    <h3 class="text-dark text-left mb-2" style="font-family: arial;">Login</h3>
     <p>Start interacting through your account</p>
    <hr style="background: black;height: 1px;">

    <br>
        <div class="mb-2">
          <label for="">Username*</label>
          <input type="text" name="username" placeholder="Enter Username" class="form-control" id="" required>
        </div>
        <br>
        <div class="mb-4">
          <label for="">Password*</label>
          <input type="password" name="password" placeholder="Enter Password"class="form-control" id="" required>
        </div>

        <button type="submit" class="btn btn-primary" style=" background-color: black; color:white">Login</button>

        <p class="text-center text-dark mt-3 mb-0" >I don't have an account? <a href="{% url 'website:register'%}" style="text-decoration: none;">Register</a> </p>
</form>
</div>
</div>
{% endif%}

{% endblock%}

src/website/templates/profile.html
{% extends 'base.html'%}
{% block content%}
<h3 class="text-dark mt-5">Hello <span class="text-warning">{{user.username}}</span>, Welcome to your profile</h3>
<div class="mt-5">
 <div class="card p-4">
    <h4 class="text-dark">These are all the functions available, {{user.username}}, in your CRM</h4>
    <div class="d-flex ">
        {% if request.user.is_superuser%}
        <a href="{% url 'website:add_record'%}" class="btn btn-dark d-block mt-3 mb-3 mr-3 " style="width: 150px;margin-right: 20px">Add Record</a>
        {% endif%}
     
        <a href="{% url 'website:logout'%}" class="btn btn-secondary d-block mt-3 mb-3" style="width: 150px;">Logout</a>
    
    </div>
    
    {% comment %} <h4>Record Number: {{user.record.count()}}</h4> {% endcomment %}
 </div>
 <a href="{% url 'website:home' %}" class="btn btn-secondary mt-5" ><i class="fa fa-fas fa-arrow-left"></i> Back</a>

</div>



{% endblock %}

src/website/templates/record.html
{% extends 'base.html'%}
{% block content%}
{% comment %} <h1>Customer Record :</h1> {% endcomment %}
<div class="card text-dark mt-3">
    <h5 class="card-header">{{customer_record.first_name| capfirst}} {{customer_record.last_name| capfirst}} <i class="fa fa-far fa-user-circle"></i></h5>
    <div class="card-body">
        <h5 class="card-title"><i class="fa fa-fas fa-info-circle"></i> Record Information </h5>
        <div class="card-title">
            <strong>First Name :</strong> {{customer_record.first_name}}
        </div>
        <div class="card-title">
            <strong>Last Name :</strong> {{customer_record.last_name}}
            </div>
            <div class="card-title">
                <strong>Email Address :</strong> {{customer_record.email}}
            </div>
            <div class="card-title">
                <strong>Phone Number :</strong> {{customer_record.phone}}
            </div>
            <div class="card-title">
                <strong>Address :</strong> {{customer_record.address}}
            </div>
            <div class="card-title">
                <strong>City :</strong> {{customer_record.city}}
            </div>
            <div class="card-title">
                <strong>Zip Code :</strong> {{customer_record.zipcode}}
            </div>
            <div class="card-title">
                <strong>Created :</strong> {{customer_record.created_at| date:"Y M d"}}

            </div>
    </div>
</div>
<br>
<br>
<a href="{% url 'website:home' %}" class="btn btn-secondary" ><i class="fa fa-fas fa-arrow-left"></i> Back</a>
{% if request.user.is_superuser%}
<a href="{% url 'website:delete_record' customer_record.id %}" onclick="return confirm('Are you sure you want to delete this record')" class="btn btn-danger" >Delete <i class="fa fa-far fa-trash-alt"></i></a>
<a href="{% url 'website:update_record' customer_record.id %}" class="btn btn-secondary" >Update Record <i class="fa fa-fas fa-wrench"></i></a>
{% endif%}
{% endblock %}

src/website/templates/register.html
{% extends 'base.html'%}
{% block content%}
<div class="col-md-6 offset-md-3">

<div style="background-color:rgba(189, 189, 189, 0.8); padding: 40px;margin-bottom: 20px;border-radius: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);">
    <h3 class="text-dark text-left mb-2" style="font-family: arial;">Create your account</h3>
     <p>Start managing your clients today!</p>
    <hr style="background: black;height: 1px; margin-bottom: 30px;">

<form action="" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        <div role="alert" class="alert alert-warning alert-dismissible fade show">
            Your Form Has Errors
            {% for field in form  %}
                {% if field.errors %}
                    {{field.errors}}
                {% endif %}
            {% endfor %}    
            <button class="btn-close" data-bs-dismiss="alert" aria-label="Close" type="button"></button>
        </div>
    {% endif %}

       {{form.as_p}}
        <button type="submit" class="btn btn-primary" style=" background-color: black; color:white">Register</button>
    <br><br>
    <p class="text-center text-dark  mb-0" >Already have an account? <a href="{% url 'website:home'%}" style="text-decoration: none;">Sign In</a> </p>
 
</form>
</div>
</div>
{% endblock%}

src/website/templates/search.html
{% extends 'base.html'%}
{% block content%}

<table class="table table-striped table-hover  table-bordered">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Address</th>
            <th scope="col">City</th>
            <th scope="col">State</th>
            <th scope="col">Created At</th>
            <th scope="col">Zipcode</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% if results %}
            {% for result in results %}
                <tr>
                    <td>{{result.id}}</td>
                    <td>{{result.first_name}}</td>
                    <td>{{result.last_name}}</td>
                    <td>{{result.email}}</td>
                    <td>{{result.phone}}</td>
                    <td>{{result.address}}</td>
                    <td>{{result.city}}</td>
                    <td>{{result.state}}</td>
                    <td>{{result.created_at| date:"Y M d"}}</td>
                    <td>{{result.zipcode}}</td>
                    <td><a href="{% url 'website:customer_record' result.id %}" class="fa-solid fa-eye text-secondary" style="color:black; text-decoration: none;"></a></td>
                </tr>
            {% endfor %}
        {% else %}
        <td colspan="11" class="text-center p-3" style="background-color: #fef2cc;">
           <span style="font-weight: 500; font-size:large;"> Not Found "{{query}}"</span>
        </td>
        {% endif %}
            
    </tbody>



</table>
<a href="{% url 'website:home' %}" class="btn btn-dark mt-3"><i class="fa fa-fas fa-arrow-left"></i> Back</a>


{% endblock %}

src/website/templates/update_record.html
{% extends 'base.html'%}
{% block content%}
<div class="col-md-6 offset-md-3">
    <div style="background-color:rgba(189, 189, 189, 0.8); padding: 40px;margin-bottom: 20px;border-radius: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);">

    <h2 style="color: black; font-family: arial;">Update Record</h2>
     <p>Start editing this record</p>
     <hr style="height: 1px; color: black;">
    <br> 
    <form action="" method="POST">
        {% csrf_token %}

        {{form.as_p}}
        <a href="{% url 'website:home' %}" class="btn btn-secondary" ><i class="fa fa-fas fa-arrow-left"></i> Back</a>
        <button type="submit" class="btn btn-primary" style=" background-color: black; color:white">Update Record</button>
        <br>
        <br>
    </form>
</div>
</div>
{% endblock%}